### ISSUE TITLE
Сбой программы при попытке запуска консоли Python, либо калькулятора полей

### ISSUE THREAD

**Issue by pratens** [nextgis/nextgisqgis#12]
при попытке запуска консоли Python, либо калькулятора полей - "сбой программы" на двух машинах
W10x64 nextGIS 17.5.0 x64
Отчет об ошибке Windows:
_Имя сбойного приложения: ngqgis.exe, версия: 0.0.0.0, метка времени: 0x591ef012
Имя сбойного модуля: MSVCR120.dll, версия: 12.0.21005.1, метка времени: 0x524f83ff
Код исключения: 0xc000041d
Смещение ошибки: 0x000000000003c583
Идентификатор сбойного процесса: 0xf24
Время запуска сбойного приложения: 0x01d2db0cbe3e584e
Путь сбойного приложения: D:\NextGIS\bin\ngqgis.exe
Путь сбойного модуля: D:\NextGIS\bin\MSVCR120.dll
Идентификатор отчета: f7e1c7cd-eeee-4c08-8e36-41654b79c589_

**Comment by BishopGIS** [comment]
Подтверждаю - воспроизводится.
@alisovenko  cудя по поведению . это таже ошибка с размером хэндла для 64 битных систем. Необхожимо изменить на переменную большего размера.

<img width="998" alt="2017-06-03 22 52 09" src="https://cloud.githubusercontent.com/assets/1708122/26756629/ad0602dc-48af-11e7-9627-94a5650dd24a.png">

**Comment by simgislab** [comment]
исправлено
