### ISSUE TITLE
Восстановление работоспособности браузера таблиц в postgis после дисконнекта-реконнекта сети

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisqgis#18]
если прицепиться к базе, а потом отключить сеть до неё (или VPN порвётся, или ноутбук из дока достанется), qgis начинает залипать и разваливаться разными способами

* на 2.18.9, если переполучить ip, в Browser panel показываются таблицы, но попытка их добавить говорить This layer is invalid

* если сконнектиться, зарефрешить список, отключить сеть, зарефрешить список, включить сеть, зарефрешить список - внутри схем остаются висеть Connection failed

*  ghb перетаскивании таблиц из Browser в карту, при дропе в соседнюю или ту же самую таблицу получаем залипший qgis, пытающийся скопировать одну в другую

**Comment by alisovenko** [comment]
на исходниках 2.14.15
* Получить список таблиц, затем переподключиться к сети, попробовать добавить таблицу из списка в QGIS - QGIS падает.
* После переподлючения к сети, список схем и таблиц корректно загружается со второго раза. Первая попытка обновления приводит к появлению сообщения о невозможности подключения.

**Comment by BishopGIS** [comment]
No feedback
