### ISSUE TITLE
Ubuntu, IdentifyPlus should be preinstalled 

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisqgis#28]
Сейчас он считается экспериментальным, после установки на ubuntu выключена галочка "Показывать экспериментальные", модуль в списке модулей не виден.

**Comment by BishopGIS** [comment]
@simgislab твоя резолюция. Сейчас в инсталлере только connetc и qms

**Comment by BishopGIS** [comment]
Пока не надо.
