### ISSUE TITLE
QGIS at Windows fails while open .dwg from nextgis trainng dataset

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisqgis#34]
Steps to reproduce:
1. Run NextGIS QGIS at Windows
2. git clone https://github.com/nextgis/testdata.git
3. Add vector layer vector/dwg/...dwg

**Comment by BishopGIS** [comment]
На Mac OS не падает. Хотя при зуме часть фич пропадает.

**Comment by BishopGIS** [comment]
Not reproduced on latest QGIS 18.04 (2.18.18)
