### ISSUE TITLE
В калькуляторе полей пропала справка

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisqgis#36]
Шаги для воспроизведения
1. Открыть NextGIS QGIS
2. Создать временный слой
3. Нажать кнопку "Калькулятор полей"
На некоторых компьютерах в окне будет справа окно справки по функциям, а на некоторых оно будет свёрнуто вправо так что его не видно, и слайдер (виджет) не видно.
Ожидаемое поведение: после установки окно калькулятора полей должно выглядеть с открытой справкой, как тут:

https://docs.qgis.org/2.14/en/docs/user_manual/working_with_vector/field_calculator.html
https://docs.qgis.org/2.14/en/_images/fieldcalculator.png

**Comment by BishopGIS** [comment]
На Windows 10 64bit QGIS 18.04 (2.18.18) не воспроизводится

**Comment by trolleway** [comment]
Воспроизводится на некоторых компьютерах под Windows, наблюдал это на тренинге на прошлой неделе.
