### ISSUE TITLE
Grass 7 not starting

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisqgis#42]
В модуле Processing есть раздел Grass, но в нём ничего не работает. 
Нужно или его починить, или убрать из processing, чтоб не отвлекал.
![image](https://user-images.githubusercontent.com/4630662/37555156-1f65a7b2-29f4-11e8-99da-4c871a817121.png)

**Comment by BishopGIS** [comment]
В нашей поставке GRASS нет. Processing это модуль стороннего разработчика не сильно связанный с QGIS и мы из него ничего убрать не можем. При этом, поведение штатное - такое же как и по поводу SAGA, OrfeToolbox и иных внешних инструментов которые прописаны в процессинге.
