### ISSUE TITLE
Saving a vector layer as GeoJSON crashes NGQ

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisqgis#50]
Win10 64, Win7 64

saving as ESRI Shape works fine
on Win7 saving point geojson worked, but polygons crashed

QGIS from osgeo4w 2.18.18 saves the same layer in GeoJSON just fine

GDAL 2.2.4 in both QGIS

[data.zip](https://github.com/nextgis/nextgisqgis/files/1959265/data.zip)

**Comment by BishopGIS** [comment]
This is GDAL issue on Windows:

> ogr2ogr -f "GeoJSON" -overwrite c:\tmp\t.geojson /vsizip/c:\tmp\data.zip/boundary-polygon.shp
ERROR 1: CPLString::vPrintf() ... buffer overrun.

**Comment by BishopGIS** [comment]
Fix in lib_gdal: https://github.com/nextgis-borsch/lib_gdal/commit/f5bce81e01b5be576d9ea049b694605cca5d168a
