### ISSUE TITLE
ngqgis виснет после закрытия редактирования модели в processing

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisqgis#52]
Шаги для воспроизведения

1. Открыть ngqgis
2. Запустить processing - создать новую модель
3. ввести в поля названия и группы test, сохранить модель в каталог по умолчанию с названием test
4. Закрыть окно редактирования модели

Текущее поведение:
После закрытия окна редактирования модели основное окно не реагирует на нажатия, необходимо перезагружать ngqgis

Наблюдается на ubuntu 18

**Comment by trolleway** [comment]
На WIndows в NextGIS QGIS 18.5.1 то же самое

**Comment by simgislab** [comment]
в 2.18.18 не воспроизводится

на Win10 в 18.5.1 висит, подтверждаю

**Comment by BishopGIS** [comment]
На Mac OS X тоже виснет 18.5.1

**Comment by BishopGIS** [comment]
Ошибка в релизе 2.18.19 а не в NextGIS QGIS
