### ISSUE TITLE
После обновления QGIS через NextGIS Installer сломался плагин QuickMapservice

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgisqgis#58]
После обновления QGIS плагин пропал из окон
![image](https://user-images.githubusercontent.com/4630662/42309372-0a6c5c90-8041-11e8-905b-7e7ed0053055.png)

**Comment by BishopGIS** [comment]
А если нажать переустановить модуль вопрос решается?

**Comment by BishopGIS** [comment]
No feedback
