### ISSUE TITLE
Rename "ngqgis" to "qgis by nextgis"

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisqgis#64]
subj

**Comment by Zverik** [comment]
Кажется, это будет не очень удачным названием — кто-то может подумать, что NextGIS присваивают себе авторство. Вероятно, проблему (сложность набора «ngq») достаточно решить переименованием в «qgis-ng».

**Comment by simgislab** [comment]
@BishopGIS давай qgis-ng
