### ISSUE TITLE
DTClassifier should check validity of input geometries

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgisqgis#72]
process shouldn't start otherwise it will crash

sample incorrect data attached
[palmno.zip](https://github.com/nextgis/nextgisqgis/files/3018284/palmno.zip)

**Comment by BishopGIS** [comment]
Use QgsGeometryValidator for first hit of invalid geometry, and stop processing with warning message.

**Comment by alisovenko** [comment]
Done with 8975af0
