### ISSUE TITLE
NextGIS installation changes path to TLS CA certificate for `pip` systemwide

### ISSUE THREAD

**Issue by kapooostin** [nextgis/nextgisqgis#74]
I'm not sure if this is a correct description of the issue, but here it is. I had installed NextGIS some time ago, then I deleted it and ever since python always tries to use its certificate:
```
Could not find a suitable TLS CA certificate bundle, invalid path: /Users/user/Applications/NextGIS/Library/Frameworks/openssl.framework/Resources/ssl/certs/cert.pem
```
I think NextGIS just gone a little bit to far changing this for a whole system. Could you help me to rectify this?

**Comment by BishopGIS** [comment]
Installer add paths to few places:

1. /Users/user/.bash_profile or /Users/user/.profile
2. /Users/user/Library/LaunchAgents

Installer usually remove everything added to the system. But in some cases (old installer version, external edits, etc) this may not happened.

For 1 - just open .bash_profile or .profile and remove broken path. After that reopen terminal.
For 2 - execute following command 

> launchctl remove setenv.CURL_CA_BUNDLE
> launchctl remove setenv.SSL_CERT_FILE

You can find installed agents using following terminal command:

> launchctl list | grep setenv

If this help please report to close this ticket.

**Comment by kapooostin** [comment]
Yes, there were `setenv.CURL_CA_BUNDLE.plist` and `setenv.SSL_CERT_FILE.plist` left as well as a few other `setenv.*.plist` files. Removing them solved the issue.

**Comment by Classman-wand** [comment]
Hello!
I faced exactly the same problem, but after deleting `setenv.*.plist` files the problem was not solved.
Tell me, please, what else could be the reason?

**Comment by cbasno** [comment]
A more comprehensive guide on how to do what BishopGIS is suggesting would be nice. I have spent the last 2 weeks trying to solve this problem because I once installed NextGIS a year ago, and then started programming.
