### ISSUE TITLE
NextGIS QGIS is currently "not responding" when opening program

### ISSUE THREAD

**Issue by ajminer** [nextgis/nextgisqgis#76]
For the past couple of days, NextGIS QGIS has been giving a pop up window immediately upon opening the software. It says NextGIS is not responding. Screen shot is attached. I did a fresh install but still get the same message. I've waited to see if it responds after some time, but unfortunately it does not. I'm running it in Windows 10. 
![image](https://user-images.githubusercontent.com/8183667/64131022-cb2dee80-cd7a-11e9-9a0e-7fc2e304d4d5.png)

**Comment by BishopGIS** [comment]
@ajminer This is usually not NextGIS QGIS issue, but some of Python plugins. 
May be `NextGIS Connect` cannot connect to your web GIS and freezes. Try to check and change connection settings.

Launch regedit.exe, open `HKEY_CURRENT_USER\Software\NextGIS\NextGIS WEB API\connections` or `HKEY_LOCAL_MACHINE\Software\NextGIS\NextGIS WEB API\connections`, find your connection and check if url, login, password are correct. You can change values in regedit, or delete registry key and setup connection using plugin UI.

**Comment by ajminer** [comment]
Everything looked correct (url, password etc), so I tried deleting the registry key and revised the setup connection using the plugin as you suggested - seems to have fixed it. Thanks so much!
