### ISSUE TITLE
Error build on linux

### ISSUE THREAD

**Issue by giaphong** [nextgis/nextgisqgis#80]
![image](https://user-images.githubusercontent.com/34709818/70113856-dbf94380-168c-11ea-93d3-3a21a3eb7aa4.png)

Please, help me???

**Comment by BishopGIS** [comment]
Show me the output of following commands:

```bash
lsb_release -a
sudo apt-cache policy libqscintilla2-qt4-dev
sudo apt-cache policy python-qscintilla2
```

**Comment by giaphong** [comment]
@BishopGIS 
![image](https://user-images.githubusercontent.com/34709818/70136857-66f33180-16bf-11ea-98a0-02248654a872.png)

I want to run this application when it is finished. But don't know how to run.
Please, help me.

**Comment by BishopGIS** [comment]
```bash
sudo make install
```

**Comment by giaphong** [comment]
![image](https://user-images.githubusercontent.com/34709818/70400100-868daf80-1a5b-11ea-92a0-d5acbf4ac942.png)

I still don't know how to run. Please help me.

**Comment by giaphong** [comment]
Thank you!!!!
