### ISSUE TITLE
Rebrand Nextgis Desktop app on Linux

### ISSUE THREAD

**Issue by giaphong** [nextgis/nextgisqgis#82]
I want to run this application when it is finished. But don't know how to run.
Please, help me.

[Desktop Entry]
Type=Application
Name=NextGIS QGIS
Version=19.12.0
GenericName=Geographic Information System
GenericName[ru]=Геоинформационная система
Icon=/usr/share/ngqgis/images/icons/qgis-icon.png
TryExec=/usr/bin/ngqgis
Exec=/usr/bin/ngqgis %F
Terminal=false
StartupNotify=false
Categories=Qt;Education;Science;Geography;
MimeType=application/x-qgis-project;image/tiff;image/jpeg;image/jp2;application/x-raster-aig;application/x-raster-ecw;application/x-raster-mrsid;application/x-mapinfo-mif;application/x-esri-shape;
Keywords=map;globe;postgis;wms;wfs;ogc;osgeo;

**Comment by BishopGIS** [comment]
```bash
sudo make install
```

**Comment by giaphong** [comment]
Thank you!!!
